version: "3.4"
services:
  partition:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - postgresql
    command: npm run dev

  postgresql:
    image: postgres
    restart: always
    container_name: postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
