version: "3.4"
services:
  partition:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./.env
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - mysql
      - postgresql
    command: npm run dev

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Billu_1234
    ports:
      - "3307:3306"
    restart: always

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Billu_1234
    ports:
      - "5434:5432"
    restart: always
